# Generated by Django 2.0.2 on 2018-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeWeight',
            fields=[
                ('keyword', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(default=1)),
                ('word_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_keywords', models.CharField(max_length=4096)),
                ('solution_keyword', models.CharField(max_length=2048)),
            ],
        ),
    ]
