# Generated by Django 2.0.2 on 2018-07-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='solution_keyword',
            new_name='solution',
        ),
    ]
