# Generated by Django 2.0.2 on 2018-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0002_auto_20180713_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativeweight',
            name='frequency',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cumulativeweight',
            name='word_count',
            field=models.FloatField(default=0),
        ),
    ]
