# Generated by Django 2.0.2 on 2018-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0003_auto_20180713_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativeweight',
            name='word_count',
        ),
        migrations.AlterField(
            model_name='cumulativeweight',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
